INSERT INTO weibo.weibo_cand (id, url, content, wb_from) VALUES (21, 'https://weibo.com/1828817187/G2P5PdnAI', '分享图片', '金耳朵兔子');
INSERT INTO weibo.weibo_cand (id, url, content, wb_from) VALUES (22, 'https://weibo.com/3186945861/G2P2Az2M8', '【老人快摔下时被一把抱住：你已不是第一次救我】2月11日，@武汉地铁运营 6号线马鹦路站，一老人乘坐电扶梯时没站稳，即将摔倒之际，立刻被身后的地铁工作人员黄婷冲上来撑住。原来，她从出站口就注意到了这位老人，担心其安全就一直“粘”在他身后，护送他出站。老人出站后，感动得不停向她鞠躬 ...展开全文c[心]', '武汉地铁运营');
INSERT INTO weibo.weibo_cand (id, url, content, wb_from) VALUES (24, 'https://weibo.com/1791808013/G2UAx4oNK', '中国足球故事。', '英超各种黑');
INSERT INTO weibo.weibo_cand (id, url, content, wb_from) VALUES (26, 'https://weibo.com/2770181480/G2TqrqnbF', '被不喜欢的人亲到后，传说中的气得炸毛，你们体会下！#搞笑#[二哈][笑cry]', '爱上吐槽的特长生');
INSERT INTO weibo.weibo_cand (id, url, content, wb_from) VALUES (28, 'https://weibo.com/5259299541/G2UAEpVWf', '#NBA# 这手活真是太6了[汗][汗]', 'YouTube篮球精选');
INSERT INTO weibo.weibo_cand (id, url, content, wb_from) VALUES (29, 'https://weibo.com/2287235162/G2OkLxUuM', '真是笑死我了这位网友家里的卧室门坏了把锁卸了也打不开弟弟被困在里面出不来然后 #搞笑#[笑cry][笑cry][笑cry][笑cry]', '搞笑公');
INSERT INTO weibo.weibo_cand (id, url, content, wb_from) VALUES (30, 'https://weibo.com/3229125510/G2OWMEdvL', '生在一个安稳的家庭，儿时没受过虐待或校园暴力，基本上身心健康地成长，长大后也没有遇到特别恶劣的渣男渣女，三观没歪。头脑一般，考了个差不多的学校，找了一份能养活自己的工作，和一个普通的人组建了一个安稳的小家，一辈子没遇到什么飞来横祸...听起来再平常不过，然而走起来才知道有多难。', '小野妹子学吐槽');
INSERT INTO weibo.weibo_cand (id, url, content, wb_from) VALUES (31, 'https://weibo.com/1192966660/G2UZODmHH', '过年了，给发现花了198洗个车……回忆了下从去年10月到现在一直没洗车……一年洗了也没5次，一年跟我跑了好多地方，雅丹沙漠跑了两次，辛苦了。大家过节好。[允悲]', '韩路');
INSERT INTO weibo.weibo_cand (id, url, content, wb_from) VALUES (32, 'https://weibo.com/2280198017/G2TzDbdxV', '【2018，有我们在，请祖国人民安过年】逝者如斯夫，2018年的新春敲响了来临的钟声。夜晚，各地的广场上烟花绽放，平日里黑灯瞎火的城镇也热闹非凡，一切幸福祥和，美满如斯。可军人的夜空却是单调的，黑暗里只有星星相伴，为了祖国人民的安宁，他们无怨也无悔，2018，依然为您守岁！（罗鑫 胡辉）[心]', '军报记者');
INSERT INTO weibo.weibo_cand (id, url, content, wb_from) VALUES (33, 'https://weibo.com/2614543117/G2FkubplB', '某航班需承运一名病重战士，需要占用9个座位，我自愿改签一分钱都不要，多名乘客自愿改签。为正能量打call，岁月静好，只因有人负重前行。感谢有你们，致敬中国军人。', '最全热门排行榜');
